module.exports = `REACT_APP_FIREBASE_API_KEY="apikey"
REACT_APP_FIREBASE_AUTHDOMAIN="domain"
REACT_APP_FIREBASE_DATABASEURL="your db"
REACT_APP_FIREBASE_PROJECTID="projectid"
REACT_APP_FIREBASE_STORAGEBUCKET="bucket number"
REACT_APP_FIREBASE_MESSAGINGSENDERID="messengerid"
REACT_APP_FIREBASE_APPID="appid"
REACT_APP_FIREBASE_MEASUREMENTID="measurementid"
`